# Use an official OpenJDK runtime as a parent image
FROM openjdk

# Set the working directory in the container
WORKDIR /app

# Copy the packaged JAR file into the container
COPY ./target/Opulent_Cabs_Graph_Api-0.0.1.jar /app/app.jar

# Expose the port that your Spring Boot application will run on
EXPOSE 7070

# Specify the command to run your application
CMD ["java", "-jar", "app.jar"]
